application: api-volunteer
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# Endpoints
- url: /_ah/spi/.*
  script: api.app

libraries:
# Endpoints
- name: endpoints
  version: 1.0
